In [6]:
import numpy as np

def chunk_mean(X_chunk):
    total = 0
    count = 0
    if X_chunk.ndim == 1:
        X = X.reshape(-1,1)
    mean = np.nanmean(X_chunk, axis=0)
    return mean

X_chunk = np.array([
    [1.0, np.nan],
    [4.0, np.nan],
])
# shape: (3 samples, 3 features)
print(chunk_mean(X_chunk))

[2.5 nan]


/var/folders/v3/6wrfqwd54x1dvfzmk37f_1bw0000gn/T/ipykernel_95580/2824900203.py:8: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(X_chunk, axis=0)


In [12]:
def chunk_variance(X_chunk, ddof=0):

    if X_chunk.ndim == 1:
        X_chunk = X_chunk.reshape(-1, 1)

    if not isinstance(ddof, int):
        raise TypeError("ddof must be an integer.")

    n = X_chunk.shape[0] - np.sum(np.isnan(X_chunk), axis=0)

    if np.any(n - ddof <= 0):
        raise ValueError("ddof is too large for the number of values.")
    
    arr_mean = chunk_mean(X_chunk)
    squared_deviation = (X_chunk - arr_mean) ** 2
    variance = np.nansum(squared_deviation, axis=0) / (n - ddof)

    return variance

X_chunk = np.array([
    [1.0, np.nan, 3.0],
    [4.0, 5.0,   6.0],
    [7.0, 8.0,   np.nan]
])

print(chunk_variance(X_chunk))


[6.   2.25 2.25]


In [14]:
def chunk_quantiles(X_chunk, q):

    if X_chunk.ndim == 1:
        X_chunk = X_chunk.reshape(-1, 1)
    
    q_arr = np.asarray(q, dtype=float)

    if np.any(q_arr < 0) or np.any(q_arr > 1):
        raise ValueError("q must be between 0 and 1.")

    percentile = np.nanpercentile(X_chunk, q_arr * 100, axis=0)

    return percentile

X_chunk = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
    [7.0, 8.0]
])
q = [0.25, 0.75]

print(chunk_quantiles(X_chunk, q))

[[2.5 3.5]
 [5.5 6.5]]


In [16]:
def chunk_histogram(X_chunk, edges):
    
    bin_indices = np.searchsorted(edges, X_chunk, side="right") - 1
    bin_indices = np.clip(bin_indices, 0, len(edges) - 2)  #  clip indices
    counts = np.bincount(bin_indices, minlength=len(edges) - 1)
    return counts

edges = np.array([2.0, 4.0, 6.0, 8.0])
X_chunk = np.array([3.0, 5.0, 99.0])

print(chunk_histogram(X_chunk,edges))

[1 1 1]
